### PR TITLE
[lexical-markdown] Fix: Prevent markdown shortcut link transformer from being too greedy

### LINKED ISSUE #8129: Bug: markdown link transformer wraps the entire line into a link
Lexical version: 0.40.0

## Steps To Reproduce

1. The string must contain a text node in the form of a markdown-like link. Insert this
   ```
   [text](https://x.com) — this is markdown link. Try to write ')'. 
   ```
2. Manually write the markdown link on the same line: `[text](https://x.com)`

Link to code example:

https://playground.lexical.dev/#doc=H4sIAAAAAAAAE51QS2rDMBC9iphNGhCOYpqG6gBdF9xdyEJY01hElsxonMQEQw_RE_YkRU5LmtJVVzPvwbzPnAGt40gVG0bQZ6AYOc-6cd4SBtCbX8AiG-dBKwmvkVrD09pGi6AhZMaDhMSDzwRIYDwxaNjkub1rmLukF4tTUcd2Lj7e3gU3LgmXRGtob-MxCO_CvhAvNAiO4kiOUczms0L8JZENhi5bTT4SDkjJxQB6OW4lWEdY84RD7_01c07mgsVwyf-l0RkyOzJdcyN06fB0bZth9d3wHzbTl2-ijhK8SVyZA1rQy_VarcvVQ_moypWEFHuq892zN8OOYh_sz2tQxb0qFIyfULPppM4BAAA

## The current behavior

Аfter the ')' character is triggered, the entire line will wrap in LinkNode. In the text part of the link, square brackets will be cut off at the edges.

https://github.com/user-attachments/assets/42a0be86-ba82-4342-984e-8935b868a1d4

## The expected behavior

Only the current link being entered is transformed

Image

## Impact of fix

In theory, this may prevent you from writing  content for an article on the use of markdown

### PR DESCRIPTION
**Pull request by etrepum**
## Description

The RegExp used for the link markdown transformer was too greedy and could match a preceding link with unbalanced brackets if two are processed on the same line.

Closes #8129
Closes #8130

## Test plan

New unit tests to confirm that import works as expected and that it now works correctly with shortcuts

### CODE REVIEW

File: packages/lexical-markdown/src/MarkdownTransformers.ts [hunk 1]
```diff
@@ -678,8 +678,9 @@ export const LINK: TextMatchTransformer = {
   importRegExp:
     /(?:\[(.+?)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))/,
   regExp:
-    /(?:\[(.+?)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))$/,
+    /(?:\[([^[\]]*(?:\[[^[\]]*\][^[\]]*)*)\])(?:\((?:([^()\s]+)(?:\s"((?:[^"]*\\")*[^"]*)"\s*)?)\))$/,
```
Comment (etrepum) [inline packages/lexical-markdown/src/MarkdownTransformers.ts:681]: I did let claude update this based on the tests I wrote, I did not thoroughly audit it to make sure that it passes the entire commonmark spec, but it does a better job than what was there before.
