### PR TITLE
Fix (Known) Table Bugs

### LINKED ISSUE #1597: Can't edit formula when inside a table cell
I can type at the end but it's impossible for me to place the cursor in the middle using my mouse

https://user-images.githubusercontent.com/193447/161524494-769a3662-66e2-4250-a505-56b9d54dfc89.mov

### LINKED ISSUE #2010: Bug: Cannot move selection below table
Lexical version: lexical playground

## Steps To Reproduce

1. insert a table inside existing text
2. start selection above table and move it down using arrows

## The current behavior
Selection gets stuck at the table bottom, instead of moving to the next line

## The expected behavior
Selection moves to the next line below the table

image

### LINKED ISSUE #2752: Bug: Cannot place cursor outside table
When inserting a table if you delete everything after and before the table, the cursor remains inside the table and you can’t add anything else after or before. To exit the table, you need to move the cursor inside a cell and press the down arrow to move below the table — see video attached.

https://user-images.githubusercontent.com/44519061/182714077-2a9dd636-80bf-4f12-a86c-2ee11bfbd829.mov

## Steps To Reproduce

1. Insert a table
2. Delete everything after and before the table
3. Click outside the table

### LINKED ISSUE #2793: Bug: Table cell breaks when content is switched from one styling to another
Table cells break when changing style of text from one type to another (for example, when inserting into a cell a "Heading 1" and then switching to normal text - see video). This behaviour seems to not appear when changing one type of list to another.

https://user-images.githubusercontent.com/44519061/183514925-52aa2f88-f7b9-4be7-9a64-e9180b399c25.mp4

## Steps To Reproduce

1. Insert a "Heading 1" into a cell
2. Press on "Normal" styling

### PR DESCRIPTION
**Pull request by tylerjbainbridge**
Long term the solution is to improve on the React-only approach MVP here (#2929) but this gets the existing solution in much better shape.

This PR fixes the following known table bugs (seen list at bottom).

Most notably, now you can change the block type within a `TableCell` without it breaking.

https://user-images.githubusercontent.com/13852400/189770404-f6fe9a07-289b-4c4e-9530-e067341cb9e8.mov

- [X] If there is no content before the table, when pressing Cmd+A and then the delete key, the table is not deleted completely. One single cell remains and the options menu popover button is misplaced.
- [X] When pressing Cmd+Shift+Delete inside a cell, the table breaks and the cell is deleted.
- [X] After deleting the table, no content can be inserted into Composer without creating a new selection.
- [X] Table cells currently break when content is switched from one type of styling to another (closes #2793).
- [X] Content from cell cannot be easily selected/ can’t move cursor inside text from cell.
- [X] Cannot place cursor outside table (closes #2752)
- [X] Closes #1597
- [X] Closes #2010 
- [X] Closes #2793

### CODE REVIEW

**Comment by tylerjbainbridge** [comment]
Will look into the failing tests tomorrow.

**Review by zurfyx — APPROVED** [review]

File: packages/lexical-table/src/LexicalTableSelectionHelpers.ts [hunk 1]
```diff
@@ -106,6 +113,7 @@ export function applyTableHandlers(
 
   // This is adjusting the focus of the selection.
   tableElement.addEventListener('mousemove', (event: MouseEvent) => {
+    // console.log({isRangeSelectionHijacked});
```
Comment (fantactuka) [inline packages/lexical-table/src/LexicalTableSelectionHelpers.ts:116]: 👆

File: packages/lexical-table/src/LexicalTableSelectionHelpers.ts [hunk 2]
```diff
@@ -597,83 +605,155 @@ export function applyTableHandlers(
...
+      const clearCell = () => {
+        const newParagraphNode = $createParagraphNode();
+        const textNode = $createTextNode();
+        newParagraphNode.append(textNode);
+        tableCellNode.append(newParagraphNode);
+        tableCellNode.getChildren().forEach((child) => {
+          if (child !== newParagraphNode) {
+            child.remove();
+          }
+        });
```
Comment (fantactuka) [inline packages/lexical-table/src/LexicalTableSelectionHelpers.ts:669]: Does it need to append first, and the clear the rest? Otherwise it can be a bit easier: 
```
tableCellNode.clear().append($createParagraphNode())
```

(Empty text node might not be needed to?)

File: packages/lexical-table/src/LexicalTableSelectionHelpers.ts [hunk 3]
```diff
@@ -597,83 +605,155 @@ export function applyTableHandlers(
...
+      };
 
+      if (
+        command === DELETE_LINE_COMMAND &&
+        parentElementNode.getPreviousSiblings().length === 0
```
Comment (fantactuka) [inline packages/lexical-table/src/LexicalTableSelectionHelpers.ts:674]: Do we need to get all siblings?
```
parentElementNode.getPreviousSibling() !== null
```

File: packages/lexical-table/src/LexicalTableSelectionHelpers.ts [hunk 4]
```diff
@@ -597,83 +605,155 @@ export function applyTableHandlers(
...
+
+      if (
+        command === DELETE_CHARACTER_COMMAND ||
+        command === DELETE_WORD_COMMAND
+      ) {
+        if (
+          selection.isCollapsed() &&
+          selection.anchor.offset === 0 &&
+          parentElementNode === nearestElementNode &&
+          nearestElementNode.getPreviousSiblings().length === 0
```
Comment (fantactuka) [inline packages/lexical-table/src/LexicalTableSelectionHelpers.ts:688]: Similar here

File: packages/lexical/src/LexicalEvents.ts [hunk 5]
```diff
@@ -761,6 +761,8 @@ function onKeyDown(event: KeyboardEvent, editor: LexicalEditor): void {
 
   const {keyCode, shiftKey, ctrlKey, metaKey, altKey} = event;
 
+  // debugger;
```
Comment (fantactuka) [inline packages/lexical/src/LexicalEvents.ts:764]: 🙈

File: packages/lexical/flow/Lexical.js.flow [hunk 6]
```diff
@@ -722,6 +722,7 @@ declare export class ElementNode extends LexicalNode {
   canInsertTextBefore(): boolean;
   canInsertTextAfter(): boolean;
   isInline(): boolean;
+  isRequiredParent(): boolean;
```
Comment (fantactuka) [inline packages/lexical/flow/Lexical.js.flow:725]: To be honest, I'm not sure I fully understand this method semantics, per code it flags tables, but what is its usage in API (e.g., when other element node need to override it). On the other hand, if it's just a temp thing to live with while we figuring out future of tables, maybe it should be prefixed with `unstanble_` or similar?

Comment (acywatson) [reply packages/lexical/flow/Lexical.js.flow:725]: I was going to comment something very similar - not sure the intent is totally conveyed by the method name. I gather I would use this when I want to check if some operation should stop at an earlier ancestor than the root?

Comment (tylerjbainbridge) [reply packages/lexical/flow/Lexical.js.flow:725]: I'm actually getting rid of this part of the PR- Gerard was working on a fix for this same issue and his solution (#3001) is a bit more robust and uses a more semantically clear method name.

File: packages/lexical-table/src/LexicalTableSelectionHelpers.ts (hunk 2 above)
Comment (tylerjbainbridge) [reply packages/lexical-table/src/LexicalTableSelectionHelpers.ts:669]: If an ElementNode is cleared it'll also remove the empty parents as well, which destroys the table.

Comment (acywatson) [reply packages/lexical-table/src/LexicalTableSelectionHelpers.ts:668]: > If an ElementNode is cleared it'll also remove the empty parents as well, which destroys the table. So we have to do it in this kind of roundabout way...

Oh I think I ran into this before and made a fix for it.

https://github.com/facebook/lexical/pull/1802

It was a little controversial at the time, so might not be the right place to talk about adding it to clear().

I still do and probably always will think it's wrong for LexicalNode.remove() to remove empty parents as well.
