### PR TITLE
fix: play `time travel` after reaching maximum range

### LINKED ISSUE #3196: Bug: unable to play `time travel` after reaching maximum range
## Steps To Reproduce

1. Open `playground.lexical.dev`
2.  Edit some text
3.  Click time travel
4.  Press the `Play/Pause` button, when input range is at max

## The current behavior
1. Time travel doesn't play from beginning, if it reached the maximum range, user has to drag the range to min and then start playing
2. Text flickers between `Play/Pause`

## The expected behavior
1. Should be able to play after reaching maximum
2. `Play/Pause` shouldn't flicker

## Video

https://user-images.githubusercontent.com/42532987/196236952-5cc6c6e7-fa13-49d9-8779-b99aff6c7713.mp4

### PR DESCRIPTION
**Pull request by shanpriyan**
Fixes #3196 

## After Fix

https://user-images.githubusercontent.com/42532987/196240849-5d891d98-d9e0-4f1a-8639-72b6098837c6.mp4

### CODE REVIEW

File: packages/lexical-react/src/LexicalTreeView.tsx [hunk 1]
```diff
@@ -189,6 +189,11 @@ export function TreeView({
           <button
             className={timeTravelPanelButtonClassName}
             onClick={() => {
+              const isStopped =
+                playingIndexRef.current === totalEditorStates - 1;
+              if (isStopped) {
+                playingIndexRef.current = 1;
+              }
```
Comment (harish-sethuraman) [inline packages/lexical-react/src/LexicalTreeView.tsx:196]:
```suggestion
              if (playingIndexRef.current === totalEditorStates - 1) {
                playingIndexRef.current = 1;
              }
```
maybe? 😛

Comment (shanpriyan) [reply packages/lexical-react/src/LexicalTreeView.tsx:196]: Yeah we can 😅

**Comment by acywatson** [comment]
Nice! Thank you.

**Review by acywatson — APPROVED** [review]
