### PR TITLE
Fix selection shifting when deleting paragraphs on android

### LINKED ISSUE #4340: Bug: When deleting text with the keyboard of a device it's also removing text to the right of the pointer.
In the editor when doing a long press of the delete key in an android device it removes the text to the right of the text pointer.

Lexical version: v0.9.2

## Steps To Reproduce

Tested device: Samgung Galaxy S22 Ultra with default keyboard

1. Go to the lexical playground https://playground.lexical.dev in the browser of an android device
2. Delete the predefined content and write a random paragraph 
3. Select in the text any point where there is still text to the right
4. keep pressing the delete key in the keyboard

## The current behavior

It deletes text to the left and right of the pointer

https://user-images.githubusercontent.com/59893365/232548029-4b6f358a-7955-475d-a83b-15948bb577cc.mp4

## The expected behavior

It should only delete text to the left of the pointer.

https://user-images.githubusercontent.com/59893365/232548647-52290174-df6f-411a-93ef-a035e819d340.mp4

### PR DESCRIPTION
**Pull request by waynetee**
## Description
Fixes #4340 

This is a second attempt to fix the abovementioned bug, following the unsuccessful attempt in #7122 (apologies for the issues introduced then)

In this PR, selection is only restored during deletion and when several other criteria have been met, this should minimise the chances of any unintended side effects.

### Before
https://github.com/user-attachments/assets/6f555449-8112-400b-8d21-ed35b249f428

### After
https://github.com/user-attachments/assets/7617e10e-faf6-4d25-b1ab-e73c5f8a0dad

### CODE REVIEW

**Review by etrepum — COMMENTED** [review]
I think the ideal approach here is to come up with a solution that does not depend on setTimeout. This kind of solution causes a lot of trouble down the line with debugging, possibly creating extra history entries, etc. even when it does work.

**Comment by waynetee** [comment]
@etrepum I agree with you that in a ideal world we would not need to use to use `setTimeout`. I did spend a significant amount of time investigating this issue and as far as I can tell originates from the browser, making a clean fix difficult.

I see a few ways forward:
1. We merge this PR
2. Rather than using `setTimeout` in the `beforeinput` handler, we apply the fix in the `selectionchange` handler. This is workable, but requires a way to sync it to the deletion event. We would likely end up with a fix not much cleaner than this and might end up having to use `setTimeout` anyways.
3. We solve the problem in the browser itself, this would be ideal, but it doesn't seem like any progress has been made on the issue since it was filed early last year https://issues.chromium.org/issues/331320419
4. You or someone else volunteers to investigate this issue to try to come up with a better fix. I would be happy to assist in this case.

I personally think this is a significant bug, it would be good if we can resolve it in a timely manner.

**Review by etrepum — COMMENTED** [review]
As far as I can tell with a Google Pixel 5 on Sauce Labs this build still has the bug

**Comment by waynetee** [comment]
Turns out the fix was skipped over by an earlier optimisation in certain cases. It should be fixed now, and I have tested it on both Pixel and Samsung, and with the SwiftKey keyboard too.

Thanks for helping to test this thoroughly.

**Review by etrepum — APPROVED** [review]
This works with the Pixel and Samsung devices I tried on browser stack with the google, samsung and microsoft keyboards. Does anyone else want to give this a test before merge? /cc @zurfyx @potatowagon

File: packages/lexical/src/LexicalEvents.ts [hunk 1]
```diff
@@ -622,6 +647,18 @@ function onBeforeInput(event: InputEvent, editor: LexicalEditor): void {
           }
           if (!shouldLetBrowserHandleDelete) {
             dispatchCommand(editor, DELETE_CHARACTER_COMMAND, true);
+            // When deleting across paragraphs, Chrome on Android incorrectly shifts the selection rightwards
+            // We save the correct selection to restore later during handling of selectionchange event
+            const selectionAfterDelete = $getSelection();
+            if (
+              IS_ANDROID_CHROME &&
```
Comment (zurfyx) [inline packages/lexical/src/LexicalEvents.ts:654]: Is it only specific to Chrome?

**Review by zurfyx — APPROVED** [review]

File: packages/lexical/src/LexicalEvents.ts (hunk 1 above)
Comment (waynetee) [reply packages/lexical/src/LexicalEvents.ts:654]: Chromium browsers, based on my testing
