### PR TITLE
[lexical][lexical-playground] Bug Fix: Support Apple Pencil

### LINKED ISSUE #7542: Bug:
Lexical version: v0.31.1

## Steps To Reproduce

1. Go to the playground on Safari using iPad with iPadOs 18.5 and an Apple Pencil
2. Tap on the screen somewhere in the editor with the Apple Pencil to move the selection
3. Using the Apple Pencil open the Insert dropdown, select Image, then insert the Sample image
4. Notice that no sample image was inserted
5. Tap with your finger on the somewhere in the document and perform the same steps
6. Notice that a Sample image was still not inserted
7. Refresh the page and perform the sample image insert using your finger
8. Notice that the image inserts fine if you avoid touching the editor with your Apple Pencil

## The current behavior

https://github.com/user-attachments/assets/26917363-3332-4db4-a1b7-906cd8c40ff4

## The expected behavior

I expect to be able to insert images using an Apple Pencil

## Impact of fix

This bug prevents anyone from interacting with Lexical using an Apple Pencil

### PR DESCRIPTION
**Pull request by circlingthesun**
## Description

Currently Apple Pencil inputs effectively breaks the editor because pen inputs do not update the selection state. This PR ensures pen input events update the selection state in the same way as touch input events.

Apple pencil inputs also create keyboard events when making scribbles. The key property for these events are undefined and broke the shortcuts plugin. This PR also fixes that.

Closes #7542

### CODE REVIEW

**Review by etrepum — DISMISSED** [review]
I can't test this but I think it looks good, assuming the extended test suite still passes!

**Review by etrepum — DISMISSED** [review]

File: packages/lexical/src/LexicalEvents.ts [hunk 1]
```diff
@@ -542,7 +542,7 @@ function onPointerDown(event: PointerEvent, editor: LexicalEditor) {
   // TODO implement text drag & drop
   const target = event.target;
   const pointerType = event.pointerType;
-  if (isDOMNode(target) && pointerType !== 'touch' && event.button === 0) {
+  if (isDOMNode(target) && pointerType !== 'touch' && pointerType !== 'pen' && event.button === 0) {
```
Comment (etrepum) [inline packages/lexical/src/LexicalEvents.ts:545]: This is needed to pass the formatting checks

```suggestion
  if (
    isDOMNode(target) &&
    pointerType !== 'touch' &&
    pointerType !== 'pen' &&
    event.button === 0
  ) {
```

**Comment by ivailop7** [comment]
> I can't test this but I think it looks good, assuming the extended test suite still passes!

I can test this, will confirm in the coming days.

**Review by ivailop7 — APPROVED** [review]
Verified it works with an Apple Pencil on an iPad.
