### PR TITLE
[lexical-table] Bug Fix: `colWidths` not imported from DOM for TableNode

### LINKED ISSUE #6685: Bug: `сolWidths` property is not serialized from html
The function `$generateNodesFromDOM` generating nodes from html works incorrectly.

The `colWidths` column length property is ignored.

## How to reproduce

1. Add a table
2. Change the column lengths
2. Serialize in html
3. Deserialize from html to nodes

### Editor State => HTML

Editor state:

```json
{
  "children": [
    {
      "children": [
        {
          "children": [
            {
              "children": [],
              "direction": null,
              "format": "",
              "indent": 0,
              "type": "tablecell",
              "version": 1,
              "backgroundColor": null,
              "colSpan": 1,
              "headerState": 0,
              "rowSpan": 1
            },
            {
              "children": [],
              "direction": null,
              "format": "",
              "indent": 0,
              "type": "tablecell",
              "version": 1,
              "backgroundColor": null,
              "colSpan": 1,
              "headerState": 0,
              "rowSpan": 1
            },
            {
              "children": [],
              "direction": null,
              "format": "",
              "indent": 0,
              "type": "tablecell",
              "version": 1,
              "backgroundColor": null,
              "colSpan": 1,
              "headerState": 0,
              "rowSpan": 1
            }
          ],
          "direction": null,
          "format": "",
          "indent": 0,
          "type": "tablerow",
          "version": 1
        }
      ],
      "direction": null,
      "format": "",
      "indent": 0,
      "type": "table",
      "version": 1,
      "colWidths": [
        163,
        92,
        92
      ]
    }
  ],
  "direction": null,
  "format": "",
  "indent": 0,
  "type": "root",
  "version": 1
}
```

```json
"colWidths": [
  163,
  92,
  92
]
```

html:

```html
<table><colgroup><col style="width: 163px;"><col style="width: 92px;"><col style="width: 92px;"></colgroup><tbody><tr><td style="border: 1px solid black; width: 75px; vertical-align: top; text-align: start;"><p><span style="white-space: pre-wrap;">1</span></p></td><td style="border: 1px solid black; width: 75px; vertical-align: top; text-align: start;"><p><span style="white-space: pre-wrap;">2</span></p></td><td style="border: 1px solid black; width: 75px; vertical-align: top; text-align: start;"><p><span style="white-space: pre-wrap;">3</span></p></td></tr></tbody></table>
```

### HTML to Editor State

html:

```html
<table><colgroup><col style="width: 163px;"><col style="width: 92px;"><col style="width: 92px;"></colgroup><tbody><tr><td style="border: 1px solid black; width: 75px; vertical-align: top; text-align: start;"><p><span style="white-space: pre-wrap;">1</span></p></td><td style="border: 1px solid black; width: 75px; vertical-align: top; text-align: start;"><p><span style="white-space: pre-wrap;">2</span></p></td><td style="border: 1px solid black; width: 75px; vertical-align: top; text-align: start;"><p><span style="white-space: pre-wrap;">3</span></p></td></tr></tbody></table>
```

Editor state:

```json
{
  "children": [
    {
      "children": [
        {
          "children": [
            {
              "children": [],
              "direction": null,
              "format": "",
              "indent": 0,
              "type": "tablecell",
              "version": 1,
              "backgroundColor": null,
              "colSpan": 1,
              "headerState": 0,
              "rowSpan": 1,
              "width": 75
            },
            {
              "children": [],
              "direction": null,
              "format": "",
              "indent": 0,
              "type": "tablecell",
              "version": 1,
              "backgroundColor": null,
              "colSpan": 1,
              "headerState": 0,
              "rowSpan": 1,
              "width": 75
            },
            {
              "children": [],
              "direction": null,
              "format": "",
              "indent": 0,
              "type": "tablecell",
              "version": 1,
              "backgroundColor": null,
              "colSpan": 1,
              "headerState": 0,
              "rowSpan": 1,
              "width": 75
            }
          ],
          "direction": null,
          "format": "",
          "indent": 0,
          "type": "tablerow",
          "version": 1
        }
      ],
      "direction": null,
      "format": "",
      "indent": 0,
      "type": "table",
      "version": 1,
      "colWidths": [
        92,
        92,
        92
      ]
    }
  ],
  "direction": null,
  "format": "",
  "indent": 0,
  "type": "root",
  "version": 1
}
```

Result:

```json
"colWidths": [
  92,
  92,
  92
]
```

Expected:

```json
"colWidths": [
  163,
  92,
  92
]
```

### PR DESCRIPTION
**Pull request by cwstra**
## Description

Currently, `lexical-table` serializes column widths to the DOM, but doesn't _read_ them. This should remedy that situation. 

Closes #6685

## Test plan

The playground does not have a convenient way to demonstrate this, though I did update the relevant unit test to incorporate reading the column width.

### CODE REVIEW

File: packages/lexical-table/src/LexicalTableNode.ts [hunk 1]
```diff
@@ -358,6 +359,19 @@ export function $convertTableElement(
...
+    let columns: number[] | undefined = [];
+    for (const col of colGroup.querySelectorAll(':scope > col')) {
+      const width = (col as HTMLElement).style.width;
+      if (!width || !PIXEL_VALUE_REG_EXP.test(width)) {
+        columns = undefined;
+        break;
+      }
+      columns.push(parseFloat(width));
+    }
+    if (columns) {tableNode.setColWidths(columns);}
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableNode.ts:373]: I don't think this will pass the prettier check, you can `npm run prettier:fix` to fix it and `npm run ci-check` to verify that the syntax/type/link checks pass locally

Comment (cwstra) [reply packages/lexical-table/src/LexicalTableNode.ts]: Done, along with patching up an e2e test that was (positively) affected by this change. Getting type errors inside of lexical-code when running the ci-check locally. 🤔

**Review by etrepum — APPROVED** [review]
Looks good!
