### PR TITLE
[lexical-react] Bug Fix: page freezes when typing a link in an overflow area

### LINKED ISSUE #6662: Bug: useCharacterLimit autolink infinite loop bug
copy text and paste to Editor, type any link in overflow node, infinite loop
(eg.[https://x.com])

```
useCharacterLimit autolink infinite loop bug
type a link in overflow node
http://x.
````

image

Lexical version: 0.17.1

## Steps To Reproduce

1. add CharacterLimitPlugin and AutoLinkPlugin or LinkPlugin
2. type a link in overflow node

Link to code example:
https://playground.lexical.dev/?isCharLimit=true

## The current behavior
infinite loop in useCharacterLimit -> $wrapOverflowedNodes

## The expected behavior
$wrapOverflowedNodes can deal autolink node or link node

## Impact of fix

Can I fix it by modify $wrapOverflowedNodes ?

see the comment below

### LINKED ISSUE #7474: Bug: Page freezes when typing a link in overflow area with Character Limit plugin enabled
When the Character Limit plugin is active in the playground, typing a link after exceeding the character limit causes the entire page to freeze and become unresponsive.

Image
Image
Image

### PR DESCRIPTION
**Pull request by kamilpitula**
## Description
Fix for an infinite loop bug caused by auto link plugin and overflow that were wrapping each other indefinitely.
Added an additional check within $wrapOverflowedNodes function that skips leaf nodes that already have an overflow parent.

Closes #7474
Closes #6662 
Closes #6668

### Before

When typing in an autolink with a character limit on, page freezes

### After

Page doesn't freeze anymore

https://github.com/user-attachments/assets/07db956b-d9a2-46ab-b2b8-e000f09d64b7

### CODE REVIEW

File: packages/lexical-react/src/shared/useCharacterLimit.ts [hunk 1]
```diff
@@ -173,6 +173,9 @@ function $wrapOverflowedNodes(offset: number): void {
 
   for (let i = 0; i < dfsNodesLength; i += 1) {
     const {node} = dfsNodes[i];
+    const hasOverflowParent = !!node
+      .getParents()
+      .find((p) => p instanceof OverflowNode);
```
Comment (etrepum) [inline packages/lexical-react/src/shared/useCharacterLimit.ts:178]: Probably makes sense to compute the full condition here since $isLeafNode is cheap and traversing the parents is not so cheap.

```suggestion
    const needsOverflowParent = $isLeafNode(node) && !$findMatchingParent(node, $isOverflowNode);
```

File: packages/lexical-react/src/shared/useCharacterLimit.ts [hunk 2]
```diff
@@ -215,7 +218,7 @@ function $wrapOverflowedNodes(offset: number): void {
           $unwrapNode(node);
         }
       }
-    } else if ($isLeafNode(node)) {
+    } else if ($isLeafNode(node) && !hasOverflowParent) {
```
Comment (etrepum) [inline packages/lexical-react/src/shared/useCharacterLimit.ts:221]:
```suggestion
    } else if (needsOverflowParent) {
```

**Review by etrepum — COMMENTED** [review]
Looks good, I like the simplicity of this solution and the addition of a test! I think using the $isOverflowNode predicate would be more idiomatic, instanceof is rarely used directly in lexical code

File: packages/lexical-react/src/shared/useCharacterLimit.ts (hunk 1 above)
Comment (kamilpitula) [reply packages/lexical-react/src/shared/useCharacterLimit.ts]: Good point! I changed the condition as you suggested.

**Review by etrepum — APPROVED** [review]
