### PR TITLE
[lexical-table] Feature: Improve logic for pasting table into table

### LINKED ISSUE #7262: Feature: Add missing rows and columns when pasting a table.
## Description
Automatically add missing rows and columns when pasting a table.

### Current Behavior

https://github.com/user-attachments/assets/a693d376-4efe-4607-86da-f92fed4745f4

### Expected Behavior

https://github.com/user-attachments/assets/ad8b3273-203d-4828-9d2a-f63f4b776940

## Impact
- Enhances user experience through more intuitive table operations.

### LINKED ISSUE #7263: Feature: When pasting a table, it does not work if there are merged cells in the target table.
## Description
When pasting a table, it does not work if there are merged cells in the target table.

### Current Behavior

https://github.com/user-attachments/assets/24dfeff4-5b77-42e1-8857-33971bfbff5f

### Expected Behavior

https://github.com/user-attachments/assets/f3df4552-ee8b-4cc3-8288-b08936b5c36a

## Impact
- Enhances user experience through more intuitive table operations.

### PR DESCRIPTION
**Pull request by takuyakanbr**
## Description

Improve how we handle pasting table into table:
- Properly account for merged cells in both tables. Presence of merged cells currently causes very buggy behavior when pasting (including the possibility of creating nested tables).
- If the current selection is a range selection, allow the table being modified to grow if necessary to contain the table being pasted. This is in line with GDocs behavior.
- If the current selection is a table selection, constrain the modifications to be within the selection boundary. This is in line with GDocs behavior.

Closes #7262
Closes #7263

## Test plan

Added E2E tests for table pasting: `npm run test-e2e-chromium Tables.spec`

### Before

https://github.com/user-attachments/assets/d2f03651-8149-4697-b1f5-b7a222d8e650

### After

https://github.com/user-attachments/assets/174211b4-c454-44e6-9e8b-c58b80fb39f5

## Additional notes

The new logic for pasting tables can be summarized as:
1. Unmerge all cells in affected area of the table being modified.
2. Expand the table being modified so that it can contain the table being pasted (if range selection).
3. Merge cells in the table being modified to match the table being pasted.
4. Set content in all affected cells to match the table being pasted.

To support the new logic, I've added a few additional table utils (in `lexical-table` package) that works on TableCellNode(s)—insert row, insert column, merge cells, unmerge cell. The logic for merging cells is taken from the `TableActionMenuPlugin` in `lexical-playground` package.

Some potential followups:
- I can't seem to be able to trigger pasting using cmd+V when there is a table selection (on Chrome). You can still use the browser context menu, but this should probably be fixed.
- Unlike GDocs, I'm not currently making multiple copies of the table being pasted when the selection boundary is larger than the size of the table being pasted. If there is interest in this, it could be a potential follow-up item.

### CODE REVIEW

File: packages/lexical-table/src/LexicalTableUtils.ts [hunk 1]
```diff
@@ -725,14 +778,132 @@ function $insertFirst(parent: ElementNode, node: LexicalNode): void {
   }
 }
 
+export function $mergeCells(cellNodes: TableCellNode[]): TableCellNode | null {
```
Comment (takuyakanbr) [inline packages/lexical-table/src/LexicalTableUtils.ts:781]: (This function, along with the helper function following it, are extracted out from the `TableActionMenuPlugin` in the `lexical-playground` package, with no change in logic.)

File: packages/lexical-table/src/LexicalTableUtils.ts [hunk 2]
```diff
@@ -262,21 +263,45 @@ export function $insertTableRow__EXPERIMENTAL(
...
+    );
+  }
+}
+
+/**
+ * Inserts a table row before or after the given cell node,
+ * taking into account any spans. If successful, returns the
+ * inserted table row node.
+ */
+export function $insertTableRowAtNode__EXPERIMENTAL(
```
Comment (takuyakanbr) [inline packages/lexical-table/src/LexicalTableUtils.ts:294]: (The "experimental" tag for insert row/column follows the existing functions that they are being extracted from. Open qns: Those function were added 2 years ago, so I'm wondering if we could promote them to non-experimental and get rid of the legacy versions.)

**Comment by etrepum** [comment]
While you're in this part of the code there's another issue with one of these table functions that is probably a simple fix: https://github.com/facebook/lexical/issues/7140

**Comment by etrepum** [comment]
Regarding the paste with cmd+V I think the problem is that the browser needs to have an active selection in order to handle paste. I think the real solution to this problem will be to create a selection in the browser that is promptly removed or otherwise specifically ignored by all of the code that tries to reconcile a change in the browser's selection to a new lexical RangeSelection (e.g. which happens while starting every update unless certain conditions are met, plus the selectionchange listener). This is probably also relevant to NodeSelection or any other custom selection. What may be needed is another hack like BlockCursorElement but for holding the browser's selection while a non-RangeSelection is in use.

File: packages/lexical-table/src/LexicalTableUtils.ts (hunk 2 above)
Comment (etrepum) [reply packages/lexical-table/src/LexicalTableUtils.ts:294]: In the case for new functions I don't think they should have these experimental names, if a function is experimental it would be better to just document it appropriately (e.g. with `@internal` if we don't want it to show up in docs). I think this naming convention was a failed experiment and not a convention worth following for new code.

**Review by etrepum — COMMENTED** [review]
I didn't do a careful audit of the code or tests but I did some manual testing and it seems to work much better now. Will approve once the functions are renamed without the EXPERIMENTAL postfix.

File: packages/lexical-table/src/LexicalTableUtils.ts (hunk 2 above)
Comment (takuyakanbr) [reply packages/lexical-table/src/LexicalTableUtils.ts]: I've renamed the new functions. For the existing "experimental" insert row/column functions, there are legacy exported functions using the same name (without the `__EXPERIMENTAL` tag) but with different APIs 😅

Comment (etrepum) [reply packages/lexical-table/src/LexicalTableUtils.ts]: hah! well I guess we need to come up with new names then, would be hard to do a proper deprecation if the call signature changes. Doesn't have to be in the scope of this PR

**Review by etrepum — APPROVED** [review]
