### PR TITLE
[lexical] Bug Fix: Remove empty parent node in nested list

### LINKED ISSUE #8117: Bug: Nested list not remove when delete selection
Lexical version:
 0.40.0
## Steps To Reproduce

1. Insert a list node with a nested list.
2. Select the entire nested list and part of the parent list.
3. Press Backspace to delete the selected content.
The nested list is not fully removed; instead, it shifts forward.
Image

Link to code example:
https://playground.lexical.dev/

## The current behavior
The nested list is not removed
## The expected behavior
The nested list is emoved

### PR DESCRIPTION
**Pull request by Senasiko**
## Description

This PR fixes an issue where removing a range that contains a nested list leaves behind an extra list item.
Closes #8117

## Test plan

image

### CODE REVIEW

File: packages/lexical/src/caret/LexicalCaretUtils.ts [hunk 1]
```diff
@@ -344,7 +344,18 @@ export function $removeTextFromCaretRange<D extends CaretDirection>(
...
+    focusBlock.remove(true);
+    while (parent) {
+      if (parent.isEmpty()) {
+        const element = parent;
+        parent = parent.getParent();
+        element.remove(true);
+      } else {
+        break;
+      }
+    }
```
Comment (etrepum) [inline packages/lexical/src/caret/LexicalCaretUtils.ts]: Could be a simpler loop here
```suggestion
    while (parent && parent.isEmpty()) {
      const element = parent;
      parent = parent.getParent();
      element.remove(true);
    }
```
