### PR TITLE
fixed issue 5181 where link address is not shown if comment is set in…

### LINKED ISSUE #5181: Bug: Can't see link url if comment is set inside link node.
If comment is added inside link, and cursor is placed inside comment node, link url is shown empty.

Lexical version:
0.12.2 (playground)

## Steps To Reproduce
1. Add link
2. Inside link add comment
3. Select comment
4. Input is shown with no URL

Video: 
https://github.com/facebook/lexical/assets/50548714/0065f9ac-47a0-462d-bab8-f8020eef817f

Image:
image

## The current behavior
After adding comment inside link, link url is not shown in input.

## The expected behavior
After adding comment inside link, link url should be visible in input.

### PR DESCRIPTION
**Pull request by btezzxxt**
as title fix #5181 

https://github.com/facebook/lexical/assets/25192107/d4fa572b-673f-4ef4-a9b2-7a2c9aedf45c

### CODE REVIEW

File: packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx [hunk 1]
```diff
@@ -59,9 +59,13 @@ function FloatingLinkEditor({
     const selection = $getSelection();
     if ($isRangeSelection(selection)) {
       const node = getSelectedNode(selection);
-      const parent = node.getParent();
-      if ($isLinkNode(parent)) {
-        setLinkUrl(parent.getURL());
+      const linkParent = $findMatchingParent(node, $isLinkNode);
+      const autoLinkParent = $findMatchingParent(node, $isAutoLinkNode);
```
Comment (zurfyx) [inline packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx:63]: Do we need this? `$isLinkNode` should match for AutoLink no?

**Review by zurfyx — APPROVED** [review]
See the comment but otherwise LGTM, thank you!

File: packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx (hunk 1 above)
Comment (btezzxxt) [reply packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx:63]: oh you are right, I don't think we'd like to match for autolinks
