### PR TITLE
[lexical-playground] fix: close link popup when user clicks out of it

### LINKED ISSUE #7665: The LinkPlugin popup remains open when the link is at the end of the content.
Lexical version: 0.32.1 (on the playground)

## Steps To Reproduce

1.  Add a link at the end of content.
2. Click anywhere outside the textarea.

Note: Clicking elsewhere in the content will cause the popup to close normally.

## The current behavior

The popup always remains open.

Image

## The expected behavior

The popup should close when it loses focus (blur).

### PR DESCRIPTION
**Pull request by achaljhawar**
## Description
Added a event listener to the FloatingLinkEditor component to ensure the link popup closes when it loses focus. 

Closes #7665 

### Before

https://github.com/user-attachments/assets/9d4d6937-1e18-46aa-be7e-806d43482bf8

### After

https://github.com/user-attachments/assets/72634740-a8bd-4c55-97db-233e04548ca5

### CODE REVIEW

File: packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx [hunk 1]
```diff
@@ -215,6 +215,26 @@ function FloatingLinkEditor({
...
 
+  useEffect(() => {
+    const editorElement = editorRef.current;
+    if (editorElement === null) {
+      return;
+    }
+    const handleBlur = (event: FocusEvent) => {
+      if (
+        editorElement.contains(event.relatedTarget as Element) === false &&
+        isLink === true
```
Comment (etrepum) [inline packages/lexical-playground/src/plugins/FloatingLinkEditorPlugin/index.tsx]:
```suggestion
        !editorElement.contains(event.relatedTarget as Element) &&
        isLink
```

**Review by etrepum — COMMENTED** [review]
This fails the formatting check, `npm run prettier:fix` should address that

**Review by etrepum — APPROVED** [review]
