### PR TITLE
[lexical][@lexical/table] Fix Ctrl+A to select all cells in table with merged cells #8074

### LINKED ISSUE #8074: Bug: Ctrl+A fails to select all cells in table with merged cells when table is the only editor content
When cells are merged in a table, pressing `Ctrl+A` does not select all cells within the table. Instead, only a subset of cells are selected, breaking the expected selection behavior for table content.

Lexical version: 0.39.0

## Steps To Reproduce

1. Insert a table into the editor.
2. Remove all other nodes from the editor, leaving only the table.
3. Merge two cells in the last column.
4. Place the cursor inside any cell of the table.
5. Press `Ctrl+A`.

Link to code example:
https://playground.lexical.dev
Video:
https://github.com/user-attachments/assets/1b57c791-df24-4244-ad27-c75c576cdc59

## The current behavior
`Ctrl+A` fails to select all cells when the table contains merged cells and is the only element in the editor.

## The expected behavior
`Ctrl+A` should select all cells within the table.

### PR DESCRIPTION
**Pull request by aldoprogrammer**
## Description
- Fix Ctrl+A so it selects all table cells (including merged cells) when a table is the only editor content.
- Add table SELECT_ALL handler that only intercepts when the table is the sole root child.
- Add regression tests: unit (SELECT_ALL scenarios) and E2E for merged-cell table-as-only-content.

## Test plan
- pnpm run test-unit -- lexical-table
- pnpm run test-e2e-chromium -- packages/lexical-playground/__tests__/e2e/Tables.spec.mjs

## Before
`Ctrl+A `fails to select all cells when the table contains merged cells and is the only element in the editor. see from issue demo #8074 

## After
Success to select all cells when the table contains merged cells and is the only element in the editor. Demo [here](https://youtu.be/c_cg4cSGMS4)

Closes #8074

### CODE REVIEW

File: packages/lexical-table/src/LexicalTablePluginHelpers.ts [hunk 1]
```diff
@@ -182,6 +187,78 @@ function $tableClickCommand(event: MouseEvent): boolean {
...
+  if (tableIndex === -1) {
+    return false; // Table not found in root children (shouldn't happen)
+  }
+
+  // STRICT: Table must be the ONLY child - no other nodes before or after
+  // This matches the bug reproduction scenario where table is the only content
+  if (rootChildren.length !== 1) {
+    // There are other nodes (even empty paragraphs) - don't intercept
+    return false;
+  }
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTablePluginHelpers.ts:209]: This is a lot of work, there are much simpler ways to find out if the table is the only child. The one with the least amount of code is probably something like this:

```ts
if (!root.is(tableNode.getParent()) || root.getChildrenSize() !== 1) {
  return false;
}
```

File: packages/lexical-table/src/LexicalTablePluginHelpers.ts [hunk 2]
```diff
@@ -352,6 +429,11 @@ export function registerTablePlugin(
       },
       COMMAND_PRIORITY_EDITOR,
     ),
+    editor.registerCommand(
+      SELECT_ALL_COMMAND,
+      $tableSelectAllCommand,
+      COMMAND_PRIORITY_HIGH,
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTablePluginHelpers.ts]: This should be the lowest priority that implements the desired behavior which is probably this:

```suggestion
      COMMAND_PRIORITY_LOW,
```

File: packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx [hunk 3]
```diff
@@ -763,7 +763,7 @@ describe('LexicalTableNode tests', () => {
                 </table>
               `,
             );
-          });
+          }, 15000);
```
Comment (etrepum) [inline packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx:768]: What's this for?

File: packages/lexical-table/src/__tests__/unit/LexicalTableExtension.test.ts [hunk 4]
```diff
@@ -324,4 +331,271 @@ describe('TableExtension', () => {
...
+        // Verify selection spans from first to last cell
+        expect(anchorCell.getKey()).toBe(firstCellMap.cell.getKey());
+        expect(focusCell.getKey()).toBe(lastCellMap.cell.getKey());
+
+        // Verify all unique cells are in the selection (merged cells should appear once)
+        const selectedNodes = selection.getNodes().filter($isTableCellNode);
+        const uniqueCellKeys = new Set(
+          selectedNodes.map((node) => node.getKey()),
+        );
+        const totalUniqueCells = new Set<string>();
```
Comment (etrepum) [inline packages/lexical-table/src/__tests__/unit/LexicalTableExtension.test.ts]: Generally the NodeKey type alias is used any time keys are being used, even though it is currently indistinguishable from string.

```suggestion
        const totalUniqueCells = new Set<NodeKey>();
```

File: packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx (hunk 3 above)
Comment (aldoprogrammer) [reply packages/lexical-table/src/__tests__/unit/LexicalTableNode.test.tsx:768]: This timeout increase is for a pre-existing test` ("Copy table with caption from an external source")` that was occasionally timing out.

**Review by etrepum — APPROVED** [review]
