### PR TITLE
[lexical] Bug Fix: Fix decorator selection regression with short-circuiting

### LINKED ISSUE #6506: Bug: Editor Crash when selecting an empty paragraph with an image
Version 0.17

The PR https://github.com/facebook/lexical/commit/71880d22f63a8f2631352a7032a22f639238b306 by @jason89521 

Introduced the following bug when upon selection of empty paragraphs it crashes the editor. 

To reproduce:
1. Clear the editor
2. Type a few empty lines
3. Add an image
4. Select over the empty lines

### PR DESCRIPTION
**Pull request by etrepum**
## Description

The fix in #5948 introduced a crashing regression because the logic doesn't short-circuit when an empty element is encountered.

Closes #6506

### Before

Crash happens after these conditions:

* Clear playground
* Insert blank line (creating empty paragraph node)
* Insert image (in a second paragraph)
* Select all

[sample url - must select all after clicking this](https://playground.lexical.dev/#doc=H4sIAAAAAAAAE72Qy2rDMBBF_-WuRaIkpC7aFroOuNBF6WKwJpZAtoQ0zoPgfy-J05Jm1ULpahiYM_dwT2DrJeZaSBjmhByjnGfjfLCZe5i3b8u7gvWZG_Gxh-mHEBS2MXckMICC7y33AqMV5JgYBokytZmSg8KOc7mACwXhgzxfST2ttRzDGcGo7gwoyAsfrhkNpSn-9AP73wtfnty6juOo4Ni3brrr6PDqrTiYtdYKxcX906fSlkJhhZIbGDiRVMx8nnxThm6WXJRY5kut8RXmO2r5rpn99FyP_1T2n1SkEKhITTu2MItquVo-VOtV9VhVCiUOuTlzm0DHNseht7c09GxRzTTGD_nMaJKOAgAA)

<details>
<summary>
example exception
</summary>

```
Error rendering tree: Expected node 47 to have a last child.

Stack:
Error: Expected node 47 to have a last child.
    at Il.getLastChildOrThrow (https://playground.lexical.dev/assets/main-CGFr7rm0.js:51:28219)
    at _a.isSelected (https://playground.lexical.dev/assets/main-CGFr7rm0.js:45:5077)
    at https://playground.lexical.dev/assets/main-CGFr7rm0.js:347:106
    at https://playground.lexical.dev/assets/main-CGFr7rm0.js:362:162
    at Array.forEach (<anonymous>)
    at MC (https://playground.lexical.dev/assets/main-CGFr7rm0.js:362:146)
    at https://playground.lexical.dev/assets/main-CGFr7rm0.js:362:224
    at Array.forEach (<anonymous>)
    at MC (https://playground.lexical.dev/assets/main-CGFr7rm0.js:362:146)
    at https://playground.lexical.dev/assets/main-CGFr7rm0.js:347:42
```
</details>

### After

Doesn't crash, has more test coverage

### CODE REVIEW

File: packages/lexical/src/LexicalNode.ts [hunk 1]
```diff
@@ -295,27 +295,16 @@ export class LexicalNode {
...
-          if (isFocusPointToLast && isFocusNodeIsParent && isLastChild) {
-            return false;
-          }
+        const firstPoint = targetSelection.isBackward()
+          ? targetSelection.focus
+          : targetSelection.anchor;
+        const firstElement = firstPoint.getNode() as ElementNode;
+        if (
+          firstPoint.offset === firstElement.getChildrenSize() &&
+          firstElement.is(parentNode) &&
```
Comment (etrepum) [inline packages/lexical/src/LexicalNode.ts:304]: It's imperative that this check is before the next one for short circuiting reasons

File: packages/lexical/src/LexicalNode.ts [hunk 2]
```diff
@@ -295,27 +295,16 @@ export class LexicalNode {
...
-          const isFocusPointToLast =
-            focus.offset === focusNode.getChildrenSize();
-          const isFocusNodeIsParent = focusNode.is(parentNode);
-          const isLastChild = focusNode.getLastChildOrThrow().is(this);
-          if (isFocusPointToLast && isFocusNodeIsParent && isLastChild) {
-            return false;
-          }
+        const firstPoint = targetSelection.isBackward()
+          ? targetSelection.focus
+          : targetSelection.anchor;
```
Comment (etrepum) [inline packages/lexical/src/LexicalNode.ts:300]: This gets rid of half the code

**Comment by etrepum** [comment]
Moving back to draft to investigate e2e test failures

**Comment by etrepum** [comment]
I can't get any of those e2e test to fail locally, I think they might be flaky

**Review by ivailop7 — APPROVED** [review]
