### PR TITLE
Bug Fix:  ContextMenu Paste option not preserving style 

### LINKED ISSUE #6720: Bug: use PASTE_COMMAND command lost some style
use PASTE_COMMAND command lost some style

Lexical version: 0.18.0

## Steps To Reproduce

1. open lexical playground and open use lexical context menu
2. clean all text, and input any text
3. select the text, click the font-size plus button, and see the text is larger
4. copy the larger text, and use the context menu to paste
5. see the new paste text

## The current behavior
The new text is small
## The expected behavior
new text is equal to the copied text font size
## Impact of fix
It can reproduce every time.

### PR DESCRIPTION
**Pull request by citruscai**
## Description
When you paste a text with a different font size or custom style using the context menu, the pasted text loses it's style and is the default style.

Closes #6720 

### Before

https://github.com/user-attachments/assets/a2d22e83-ca36-4fff-a9e2-02b27dca678b

### After

https://github.com/user-attachments/assets/3428907e-bbaa-4dac-8349-3b5b687b8a02

### CODE REVIEW

File: packages/lexical/src/nodes/LexicalTextNode.ts [hunk 1]
```diff
@@ -1358,7 +1358,7 @@ function applyTextFormatFromStyle(
     if (shouldApply && !lexicalNode.hasFormat(shouldApply)) {
       lexicalNode.toggleFormat(shouldApply);
     }
-
+    lexicalNode.setStyle(style.cssText);
```
Comment (etrepum) [inline packages/lexical/src/nodes/LexicalTextNode.ts:1361]: This is one workaround it but it breaks other things, it's not generally desirable or backwards compatible for *all* styles to be imported because the editor doesn't know how to work with most of the styles available in CSS and you would be stuck with them since you can't manage them from the editor. For example if you pasted some text with margins or padding or something like that you wouldn't really be able to get rid of it without deleting the text.

Comment (etrepum) [reply packages/lexical/src/nodes/LexicalTextNode.ts:1361]: In this particular case, the solution should be implemented such that it *only* works in the playground via some configuration and doesn't change the existing import behavior of TextNode

Comment (citruscai) [reply packages/lexical/src/nodes/LexicalTextNode.ts:1361]: so

> In this particular case, the solution should be implemented such that it _only_ works in the playground via some configuration and doesn't change the existing import behavior of TextNode

should i do something similiar like the above code? such as only supporting certain custom styles like font size and background color and not sure what else

Comment (etrepum) [reply packages/lexical/src/nodes/LexicalTextNode.ts]: Yes, but in order to maintain backwards compatibility the code has to be done somewhere else. I replied to your discord with an untested sketch of some code that will probably get close, using the html import configuration option that will be documented via https://github.com/facebook/lexical/issues/6762

**Review by etrepum — DISMISSED** [review]
This is looking pretty good, only a small suggestion left! Let's see if this affects any of the e2e tests that will run after approval

File: packages/lexical-playground/__tests__/e2e/CopyAndPaste/lexical/ContextMenuCopyAndPaste.spec.mjs [hunk 2]
```diff
@@ -52,4 +52,44 @@ test.describe('ContextMenuCopyAndPaste', () => {
       `,
     );
   });
+  test('Rich text Copy and Paste', async ({page, isRichText}) => {
+    test.skip(isRichText);
```
Comment (etrepum) [inline packages/lexical-playground/__tests__/e2e/CopyAndPaste/lexical/ContextMenuCopyAndPaste.spec.mjs:56]: I think this is backwards

```suggestion
    test.skip(!isRichText);
```

**Comment by citruscai** [comment]
> This is looking pretty good, only a small suggestion left! Let's see if this affects any of the e2e tests that will run after approval

yipee!!

**Comment by citruscai** [comment]
@etrepum  just fixed font size, the regex was returning null. now trying to fix background color and color

**Review by etrepum — APPROVED** [review]
Everything looks good, only one test failure this run and it's a flaky test that has passed before and passes locally for me. In the last commit I added some extra locking around clipboard related tests to hopefully make them more reliable.

I think this is good to go and will get merged shortly. Great work!
