### PR TITLE
Fix table stealing selectionchange

### LINKED ISSUE #3785: Bug: Cannot deselect selected playground content when selection includes a table and some other content
Lexical version: current playground version

## Steps To Reproduce

1. Start with the Lexical playground
2. Add a table
3. Click and drag a selection that includes both some part of the table, or even all of it, and some other text content on the page as well.

## The current behavior
A mouse click anywhere does not automatically deselect the selection.

## The expected behavior
A mouse click anywhere should deselect the selection, as it does in all other playground contexts.

### LINKED ISSUE #4138: Bug: Table prevents text deselection
As soon as a table is added to the rich-text-editor, the text (de)selection is bugged. 

Lexical version: 0.9.0

## Steps To Reproduce

1. Insert a table node into the editor. You can reproduce the issue in the playground (https://playground.lexical.dev/)
2. Select some text outside the table
3. Try to move the caret to a position inside the selected text. It won't work. You can only clear the selection by clicking elsewhere.

If you remove the table again, everything works as expected again.

### PR DESCRIPTION
**Pull request by zurfyx**
Turns out that the `mouseDown` logic inside the table plugin was handling more events than it should.

https://user-images.githubusercontent.com/193447/226449211-70ead2ad-3f37-4cf7-9565-4e007d6a7bac.mov

Fixes #3785 
Fixes #4138

### CODE REVIEW

**Review by tylerjbainbridge — APPROVED** [review]
good catch!

File: packages/lexical-table/src/LexicalTableSelectionHelpers.ts [hunk 1]
```diff
@@ -141,21 +142,29 @@ export function applyTableHandlers(
```
Comment (fantactuka) [inline packages/lexical-table/src/LexicalTableSelectionHelpers.ts:142]: Is this one needed at all?

**Review by fantactuka — APPROVED** [review]

**Review by thegreatercurve — APPROVED** [review]

File: packages/lexical-table/src/LexicalTableSelectionHelpers.ts (hunk 1 above)
Comment (zurfyx) [reply packages/lexical-table/src/LexicalTableSelectionHelpers.ts:142]: Discussed offline; let's leave this for now as the comment above is important

```
  // Select entire table at this point, when grid selection is ready.
```

Basically means that it wasn't implemented yet 🙃
