### PR TITLE
Clone objects from the CSS cache before mutating them

### LINKED ISSUE #3944: Bug: When setting styles on a collapsed selection, the styles object is not copied.
Lexical version: 59990233d496f50a365e68008df4bba2ade6aaf4 (0.8.0 branch)

## Steps To Reproduce

```ts
$getSelectionStyleValueForProperty($getSelection(), 'color', '');

$patchStyleText($getSelection(), {color: 'red'});

$getSelection().setStyle('');

$getSelectionStyleValueForProperty($getSelection(), 'color', '');
```

## The current behavior

The final call to `$getSelectionStyleValueForProperty` returns `'red'`.

## The expected behavior

It should return an empty string.

## Analysis

The problem is that the initial call to `$getSelectionStyleValueForProperty` will populate the CSS style cache (`CSS_TO_STYLES`) with an empty string pointing to an empty object then the subsequent call to `$patchStyleText`, when it operates on a collapsed selection, will directly modify that object without first cloning it.

### PR DESCRIPTION
**Pull request by birtles**
Fixes #3944.

This patch also fixes a bug in $getSelectionStyleValueForProperty that
was papered over by this bug--namely that when it is called on
a collapsed selection we should report the style on the selection
regardless of whether it agrees with the current node style.

### CODE REVIEW

**Comment by birtles** [comment]
After posting this, I was thinking I might try to drop the change to `$isTextNode` and try adding a `Readonly<>` annotation to the result of `getStyleObjectFromCSS` to catch bugs like this earlier.

**Comment by birtles** [comment]
This is ready for review now.

I reverted the change to `$isTextNode` since, if we change the `$isXXXNode` helpers to take an `unknown` input, we should probably change all of them at the same time.

Also, I _haven't_ updated the return type of `getStyleObjectFromCSS` to `Readonly<>` yet because it turns out that function is exported so doing so is a potentially breaking change which should probably be made separately. I'll file a separate issue for that.

File: packages/lexical-selection/src/lexical-node.ts [hunk 1]
```diff
@@ -247,11 +247,13 @@ export function $addNodeStyle(node: TextNode): void {
   CSS_TO_STYLES.set(CSSText, styles);
 }
 
-function $patchNodeStyle(
-  node: TextNode,
+function $patchStyle(
```
Comment (thegreatercurve) [inline packages/lexical-selection/src/lexical-node.ts:250]: I know it's probably not DRY, but to avoid shipping this as a breaking change, can we use the original method of `$patchNodeStyle`, but also add `$patchSelectionStyle`?

**Review by thegreatercurve — COMMENTED** [review]
LGTM, but can we make one change to avoid having to ship this as a breaking change.

File: packages/lexical-selection/src/lexical-node.ts (hunk 1 above)
Comment (birtles) [reply packages/lexical-selection/src/lexical-node.ts:250]: Sure, can do. But just to check, why would this be a breaking change? Is $patchNodeStyle exported somewhere? (Sorry, on a phone now where it's hard to check)

Comment (thegreatercurve) [reply packages/lexical-selection/src/lexical-node.ts:250]: Sorry @birtles, my mistake, I'm confusing this with another similarly named method we do export.

**Review by thegreatercurve — APPROVED** [review]
