### PR TITLE
Fix inlines in insertParagraph

### LINKED ISSUE #1678: Bug: Enter will split a link and move the second part to next paragraph
Lexical version: The latest version on https://lexical-playground.vercel.app/

## Steps To Reproduce

Check the video below. 

Link to code example: N/A

## The current behavior

https://user-images.githubusercontent.com/24715727/163252913-bd0594f7-3408-490a-b6b8-9a5ab6944471.mp4

## The expected behavior

This is what I expected when I press Enter:
image

### PR DESCRIPTION
**Pull request by acywatson**
Fixes #1678 

~~I'm not sure this is actually the right way to handle this though. The logic in this function is sort of messy, and this change certainly doesn't help things. It's also pretty specific to LinkNodes (the only thing implementing isInline right now) in that it basically assumes that the inline element has just a TextNode in it.~~

This function might be something we need to think about refactoring or totally rethinking. I want to add some tests here to catch weird behavior.

EDIT:

I was able to implement a solution that I think it more robust and should handle most cases of inline elements. Still thing we might be able to refactor this function, but I'm concerned about bloating core if we add a bunch of sub-functions to make it more readable.

### CODE REVIEW

File: packages/lexical/src/LexicalSelection.js [hunk 1]
```diff
@@ -1380,11 +1387,19 @@ export class RangeSelection implements BaseSelection {
...
         for (let i = 0; i < nodesToMoveLength; i++) {
           const nodeToMove = nodesToMove[i];
           if (firstChild === null) {
+            if (isInline) {
+              // For inline nodes, we start with the nodes that were previously in the parent
+              newElement.getParentOrThrow().append(nodeToMove);
+            } else {
+              newElement.append(nodeToMove);
+            }
+          } else if (isInline && i === nodesToMoveLength - 1) {
```
Comment (acywatson) [inline packages/lexical/src/LexicalSelection.js:1401]: This assumes that the inline element only has one node to be added to it, which is wrong. I am thinking through how I want to make this work. You can break it now by putting bold text in a link, which gives you several link nodes

**Comment by trueadm** [comment]
I think adding a bunch of e2e tests around this will help you refine your logic accordingly.

File: packages/lexical/src/LexicalSelection.js [hunk 2]
```diff
@@ -1368,19 +1370,41 @@ export class RangeSelection implements BaseSelection {
...
-      const nodesToMoveLength = nodesToMove.length;
-      // Move the new element to be before the current element
-      if (anchorOffset === 0 && nodesToMoveLength > 0) {
+      // If we're at the beginning of the current element, move the new element to be before the current element
+      const currentElementFirstChild = currentElement.getFirstChild();
+      const isBeginning =
+        anchorOffset === 0 &&
+        (currentElement.is(anchor.getNode()) ||
+          (currentElementFirstChild &&
+            currentElementFirstChild.is(anchor.getNode())));
```
Comment (harish-sethuraman) [inline packages/lexical/src/LexicalSelection.js:1393]: May be?
```suggestion
          (currentElementFirstChild?.is(anchor.getNode())));
```

Comment (acywatson) [reply packages/lexical/src/LexicalSelection.js:1393]: We actually avoid using that syntax in this repo - I believe it's because GCC doesn't handle it properly and we didn't want to add a transpilation step to the build pipeline for it.

Comment (harish-sethuraman) [reply packages/lexical/src/LexicalSelection.js:1393]: Got it thanks :)

**Review by trueadm — APPROVED** [review]
Looks awesome!

**Review by zurfyx — APPROVED** [review]
🙇‍♂️
