### PR TITLE
keep selection style when clicking empty editor

### LINKED ISSUE #5202: Bug: Lexical Playground bug & Lexical internal logic bug in every lexical version
Lexical version: every version

## Steps To Reproduce

https://github.com/facebook/lexical/assets/78121870/1ec772c8-4511-4d07-8e4b-e1cb685e59e0

1. select `20px` in toolbar 
2. click editor 

Link to code example:

## The current behavior
- reset default fontSize

## The expected behavior
- keep current style

I found what makes bug.  [onSelectionChange](https://github.com/facebook/lexical/blob/ed8f85fb5e5106dba237e2a166e57acaa28e8fbe/packages/lexical/src/LexicalEvents.ts#L258) has below logic.

```typescript
        if (
          currentTimeStamp < timeStamp + 200 &&
          anchor.offset === lastOffset &&
          anchor.key === lastKey
        ) {
          selection.format = lastFormat;
          selection.style = lastStyle;
      }
```

If conditional statement is true, It works expected. but `currentTimeStamp < timeStamp + 200` is false. 
What is the intention of this code??

### PR DESCRIPTION
**Pull request by youngkyo0504**
resolve #5202 

change code to keep selection style when clicking editor which has empty content.

`before`

https://github.com/facebook/lexical/assets/78121870/c2198c28-e190-4efe-886c-03ed20e4be80

`after`

https://github.com/facebook/lexical/assets/78121870/01f0deb7-5b65-4e01-b77a-cdaf16a85bc1

### CODE REVIEW

**Comment by ivailop7** [comment]
@youngkyo0504 can you sign the CLA and I'm OK with merging this.

**Comment by youngkyo0504** [comment]
> @youngkyo0504 can you sign the CLA and I'm OK with merging this.

Thank you! I have signed the CLA 😁

File: packages/lexical/src/LexicalEvents.ts [hunk 1]
```diff
@@ -11,6 +11,7 @@ import type {NodeKey} from './LexicalNode';
 import type {ElementNode} from './nodes/LexicalElementNode';
 import type {TextNode} from './nodes/LexicalTextNode';
 
+import {$isRootTextContentEmpty} from '@lexical/text';
```
Comment (acywatson) [inline packages/lexical/src/LexicalEvents.ts:14]: I don't think we should create this dependency between the core and @lexical/text

**Review by acywatson — CHANGES_REQUESTED** [review]

File: packages/lexical/src/LexicalEvents.ts (hunk 1 above)
Comment (youngkyo0504) [reply packages/lexical/src/LexicalEvents.ts:14]: @acywatson 

how about using this instead of delete dependency? 

```ts
const root = $getRoot();
isRootEmpty  root.getTextContent() === ''
```

**Review by acywatson — APPROVED** [review]
