### PR TITLE
[lexical-table][lexical-playground] Feature: Add column widths to TableNode

### LINKED ISSUE #6623: Bug: table resizes wrong column when cell is merged
This a bug in the playground, but is relevant to anyone trying to implement table resizing.

When you resize a merged table cell, the column the cell starts in is resized, rather than the column where you're dragging.

Demo:

https://github.com/user-attachments/assets/1959cc03-f90e-4dbd-a0c9-33ca7c2311b9

Lexical version: v0.17.1

## Steps To Reproduce

1. create a column with >3 columns and > 2 rows
2. merge any cell in the first column with the cell to it's right
3. resize the right hand side of the merged cell

## The current behavior

The size of the first column is updated

## The expected behavior

The second column is expected to change size.

## Impact of fix
- Low severity
- Any user implementing tables would benefit from improvements
- Fix would contribute to the overall quality of tables in lexical

### PR DESCRIPTION
**Pull request by patrick-atticus**
## Description

This PR adds an optional `colWidths` property to TableNode, which renders a `<colgroup>` element within tables. 

Defining the column widths has 2 main advantages:
1. We can simplify table resizing logic, particularly around merged cell cases.
2. It enables better control of tables with the style `table-layout: fixed`

If using `table-layout: fixed`, you must set a table width. Lexical playground uses `max-content` which masks some issues. If you want to truncate text within the table, the best way is to change the table width to `fit-content` (and add css to truncate). 

However, without a `<col>` element, a table with layout `fixed` will use the first row to determine column widths for the rest of the table. If there are merged cells in the first row, this makes it impossible to correctly size (and resize) columns in the remaining rows.

Adding `colWidths` to TableNode is the cleanest way to enable the ability to truncate text in tables and simplify resizing.

### Changes
- Add optional `colWidth` to TableNode (an array of pixel width numbers)
- Update `createDOM` to render `<colgroup>` and `<col>` elements with widths, if `colWidths` is set.
- Update playground `TableCellResizerPlugin` to get and set `colWidths` for better resizing

Closes #6623 #6624 (resize bugs)

Now it is also possible to truncate text in cells. This was not possible before and is the main motivation for this PR

## Test plan

Since this changes the output of TableNode, it breaks many tests that expect specific HTML. I will update tests if maintainers are open to this approach.

### Demo
🔉 narrated
https://github.com/user-attachments/assets/aa7902f2-df6f-4975-b83c-2a28e7f086c5

### CODE REVIEW

File: packages/lexical-playground/src/plugins/TableCellResizer/index.tsx [hunk 1]
```diff
@@ -242,7 +231,7 @@ function TableCellResizer({editor}: {editor: LexicalEditor}): JSX.Element {
     for (let row = 0; row < tableMap.length; row++) {
       for (let column = 0; column < tableMap[row].length; column++) {
         if (tableMap[row][column].cell === tableCellNode) {
-          return column;
+          return column + tableCellNode.getColSpan() - 1;
```
Comment (etrepum) [inline packages/lexical-playground/src/plugins/TableCellResizer/index.tsx:234]: I think this fix would be nice to have outside of this PR

File: packages/lexical-table/src/LexicalTableNode.ts [hunk 2]
```diff
@@ -59,13 +82,24 @@ function setRowStriping(
...
 
+  getColWidths() {
+    const self = this.getLatest();
+    return self.__colWidths;
+  }
+
+  setColWidths(colWidths: number[]) {
+    const self = this.getWritable();
+    self.__colWidths = colWidths;
+  }
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableNode.ts:99]: By convention setters are chainable in Lexical (this isn't totally consistent yet)

```suggestion
  setColWidths(colWidths: number[]): this {
    const self = this.getWritable();
    self.__colWidths = colWidths;
    return self;
  }
```

File: packages/lexical-table/src/LexicalTableNode.ts [hunk 3]
```diff
@@ -83,19 +117,21 @@ export class TableNode extends ElementNode {
...
     tableNode.__rowStriping = serializedNode.rowStriping || false;
     return tableNode;
   }
 
-  constructor(key?: NodeKey) {
+  constructor(colWidths?: number[], key?: NodeKey) {
     super(key);
     this.__rowStriping = false;
+    this.__colWidths = colWidths;
   }
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableNode.ts:129]: For compatibility it would be better to leave this out of the constructor and put it in `afterCloneFrom`.

```suggestion
  constructor(key?: NodeKey) {
    super(key);
    this.__rowStriping = false;
  }
```

File: packages/lexical-table/src/LexicalTableNode.ts [hunk 4]
```diff
@@ -59,13 +82,24 @@ function setRowStriping(
...
+  }
+
+  setColWidths(colWidths: number[]) {
+    const self = this.getWritable();
+    self.__colWidths = colWidths;
+  }
+
   static clone(node: TableNode): TableNode {
-    return new TableNode(node.__key);
+    return new TableNode(node.__colWidths, node.__key);
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableNode.ts:102]:
```suggestion
    return new TableNode(node.__key);
```

File: packages/lexical-table/src/LexicalTableNode.ts [hunk 5]
```diff
@@ -83,19 +117,21 @@ export class TableNode extends ElementNode {
   }
 
   static importJSON(serializedNode: SerializedTableNode): TableNode {
-    const tableNode = $createTableNode();
+    const tableNode = $createTableNode(serializedNode.colWidths);
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableNode.ts:120]:
```suggestion
    const tableNode = $createTableNode();
    tableNode.__colWidths = serializedNode.colWidths;
```

File: packages/lexical-table/src/LexicalTableNode.ts [hunk 6]
```diff
@@ -306,8 +358,8 @@ export function $convertTableElement(
   return {node: tableNode};
 }
 
-export function $createTableNode(): TableNode {
-  return $applyNodeReplacement(new TableNode());
+export function $createTableNode(colWidths?: number[]): TableNode {
+  return $applyNodeReplacement(new TableNode(colWidths));
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableNode.ts:362]:
```suggestion
export function $createTableNode(): TableNode {
  return $applyNodeReplacement(new TableNode());
```

File: packages/lexical-table/src/LexicalTableUtils.ts [hunk 7]
```diff
@@ -471,6 +471,13 @@ export function $insertTableColumn__EXPERIMENTAL(insertAfter = true): void {
   if (firstInsertedCell !== null) {
     $moveSelectionToCell(firstInsertedCell);
   }
+  const colWidths = grid.getColWidths();
+  if (colWidths) {
+    const columnIndex = insertAfterColumn < 0 ? 0 : insertAfterColumn;
+    const newWidth = colWidths[columnIndex];
+    colWidths.splice(columnIndex, 0, newWidth);
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableUtils.ts:478]: This is going to break history because you're mutating the array in-place, a new array needs to be created for this

File: packages/lexical-table/src/LexicalTableUtils.ts [hunk 8]
```diff
@@ -643,6 +650,11 @@ export function $deleteTableColumn__EXPERIMENTAL(): void {
     const {cell} = previousRow;
     $moveSelectionToCell(cell);
   }
+  const colWidths = grid.getColWidths();
+  if (colWidths) {
+    colWidths.splice(startColumn, selectedColumnCount);
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableUtils.ts:655]: Another in-place mutation of the node state

**Review by etrepum — COMMENTED** [review]
Overall this seems like a great approach. There are going to be some issues with sharing of `__colWidths` because node properties can not be shared across versions (unless they are effectively immutable). Removing the rest of the width support from TableCellNode would also make sense, and of course fixing the tests is going to be the big thing.

File: packages/lexical-playground/src/plugins/TableCellResizer/index.tsx (hunk 1 above)
Comment (patrick-atticus) [reply packages/lexical-playground/src/plugins/TableCellResizer/index.tsx:234]: Good call, this is really a separate issue https://github.com/facebook/lexical/pull/6630

**Comment by patrick-atticus** [comment]
@etrepum thanks for the review!

> There are going to be some issues with sharing of __colWidths because node properties can not be shared across versions (unless they are effectively immutable).

Could you please expand on this? I'm not sure what this means

I'll take a look at the tests

**Comment by patrick-atticus** [comment]
Thanks, I assume there's no other nodes that do this at the moment? Would it be enough to type the property as `readonly`, and `Object.freeze` the value in the setter? (see recent commit)

This worked well to flag an error in another place I had mutated it.

**Comment by etrepum** [comment]
Using the readonly type is probably sufficient, we don't do a lot of runtime enforcement of these kinds of constraints that the type checker can enforce especially in production. Copying it everywhere even when not necessary is something to be avoided (e.g. copying in the setter, getter and clone would be most robust but do unnecessary work pretty often).

It's not done a lot in this codebase, I can't think of many properties that are a mutable type to begin with. It's normally primitive value types that don't have any sort of sharing issues.

File: packages/lexical-table/src/LexicalTableNode.ts [hunk 9]
```diff
@@ -85,6 +121,7 @@ export class TableNode extends ElementNode {
   static importJSON(serializedNode: SerializedTableNode): TableNode {
     const tableNode = $createTableNode();
     tableNode.__rowStriping = serializedNode.rowStriping || false;
+    tableNode.__colWidths = Object.freeze(serializedNode.colWidths);
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableNode.ts:124]:
```suggestion
    tableNode.__colWidths = serializedNode.colWidths;
```

File: packages/lexical-table/src/LexicalTableNode.ts [hunk 10]
```diff
@@ -59,17 +82,30 @@ function setRowStriping(
 export class TableNode extends ElementNode {
   /** @internal */
   __rowStriping: boolean;
+  __colWidths?: readonly number[];
 
   static getType(): string {
     return 'table';
   }
 
+  getColWidths() {
```
Comment (etrepum) [inline packages/lexical-table/src/LexicalTableNode.ts:91]:
```suggestion
  getColWidths(): readonly number[] {
```

**Comment by etrepum** [comment]
It looks like the tests are passing, when you think it's ready for review (this PR is still in draft) and then we'll review it again and merge when ready

**Comment by patrick-atticus** [comment]
There's a lot of noise from fixing the tests, but I've tried to keep the commits clean.

I added one unit test that covers setting widths and inserting a column. The e2e tests have some resizing merged cells which verifies the colwidth output. Let me know if there's any other cases you'd like covered.

As far as I can tell the remaining failures are due to flakes.

**Comment by etrepum** [comment]
I think the remaining failures are not just flaky, I gave the failed tests a couple additional runs. Some of it is HTML differences because of the added `colgroup`

```
[1]   2 failed
[1]     [chromium] › packages/lexical-playground/__tests__/e2e/Tables.spec.mjs:2277:3 › Tables › Select multiple merged cells (selection expands to a rectangle) 
[1]     [chromium] › packages/lexical-playground/__tests__/e2e/Tables.spec.mjs:3378:3 › Tables › Can align text using Table selection 
```

**Comment by patrick-atticus** [comment]
Ah I see now, thank you. Fixed.

As a side note, I wasn't able to run the collab e2e tests locally. With the server running `npm run start` and the collab tests  eg `npm run test-e2e-collab-chromium` the playground connection button state always starts as disconnected:

```
      -   unexpected value "Connect Collaborative Editing"


       at packages/lexical-playground/__tests__/utils/index.mjs:119

      117 |         await expect(
      118 |           frameLocator.locator('.action-button.connect'),
    > 119 |         ).toHaveAttribute('title', /Disconnect/);
```

**Comment by etrepum** [comment]
Ah that's interesting, it looks like there's a dev mode collab bug probably due to react strict mode. I think because the effects run twice the provider is disconnecting the websocket, I wonder when that started. The ci versions appear to work (although those also trigger a build which can be a bit slower to start).

**Review by etrepum — APPROVED** [review]
Thank you for all your work on this!

**Comment by patrick-atticus** [comment]
Thanks! Keen to make use of this
