### PR TITLE
Fix Clear Formatting (Fixes #4188)

### LINKED ISSUE #4188: Bug: Clear formatting doesn't respect the selected text
Lexical version: 0.9

## Steps To Reproduce

1. Bold a few words
2. Select one of those words
3. Click "Clear Formatting"

## The current behavior vs the expected behavior

It clears the formatting for the entire editor text vs just the selected text

### PR DESCRIPTION
**Pull request by ivailop7**
Clear formatting respects the selection, also converts Headings and Quotes down to Paragraphs, but doesn't convert Code Blocks or any list types, matching the behaviour of other popular text editors.

Before:

https://user-images.githubusercontent.com/7893468/227743734-7101ae98-10a0-4af2-baca-ccfaf612f58d.mp4

After:

https://user-images.githubusercontent.com/7893468/227743740-8ab0ae0b-2d51-47a1-888b-d30c9f1c8d97.mp4

### CODE REVIEW

**Comment by ivailop7** [comment]
@fantactuka could you help me out how to replace a HeadingNode with a TextNode. I tried
```javascript
node.replace(new TextNode('abc'), false);
```
but I get an error that I can only add an Element or a Decorator node to the Root node. What would be the right syntax here?

**Comment by acywatson** [comment]
@ivailop7 you need to wrap the TextNode in a ParagraphNode (or some other element). They can’t exist as direct children of the root.

**Comment by ivailop7** [comment]
> @ivailop7 you need to wrap the TextNode in a ParagraphNode (or some other element). They can’t exist as direct children of the root.

Understood. Thank you @acywatson .

**Comment by ivailop7** [comment]
Updated. The CI failing post the Excalidraw update I believe is because of the parallelization of the tests, thus the sporadic success/failure. I believe it has to be moved from package.json inside the playground to the root one, but needs proper investigation, this is just a theory. Might dig into that one soon.

File: packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx [hunk 1]
```diff
@@ -538,14 +538,30 @@ export default function ToolbarPlugin(): JSX.Element {
...
+        nodes.forEach((node, idx) => {
+          // We split the first and last node by the selection
+          // So that we don't format unselected text inside those nodes
           if ($isTextNode(node)) {
+            if (idx === 0 && anchor.offset !== 0) {
+              node = node.splitText(anchor.offset)[1];
+            }
+            if (idx === nodes.length - 1) {
+              node = node.splitText(focus.offset)[0];
+            }
```
Comment (zurfyx) [inline packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx:558]: Should we check whether format is already `0` and style is `''`? This will prevent unnecesarily splitting a node

File: packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx [hunk 2]
```diff
@@ -538,14 +538,30 @@ export default function ToolbarPlugin(): JSX.Element {
...
             node.setFormat(0);
             node.setStyle('');
             $getNearestBlockElementAncestorOrThrow(node).setFormat('');
-          }
-          if ($isDecoratorBlockNode(node)) {
+          } else if ($isHeadingNode(node) || $isQuoteNode(node)) {
+            node.replace($createParagraphNode(), true);
```
Comment (zurfyx) [inline packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx:563]: Is this what's expected out of clear formatting? My hunch is that clear formatting should only clear the above (style + format) but the nodes should be left intact. What makes you think this is the correct behavior? I'm looking at Quip for example

File: package.json [hunk 3]
```diff
@@ -103,6 +103,7 @@
     "@babel/preset-flow": "^7.14.5",
     "@babel/preset-react": "^7.14.5",
     "@babel/preset-typescript": "^7.16.7",
+    "@excalidraw/excalidraw": "^0.14.2",
```
Comment (zurfyx) [inline package.json:106]: Let's drop this and package-lock.json, I'm not sure why GH cache is sometimes bad but we can retry when this happens. Definitely something worth investigating but the package should live inside the playground

**Review by zurfyx — APPROVED** [review]
Thank you! Adding some minor comments

File: packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx (hunk 1 above)
Comment (ivailop7) [reply packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx:558]: This is the behaviour in Word.

File: packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx (hunk 2 above)
Comment (ivailop7) [reply packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx:563]: This is the behaviour in Word.

File: packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx (hunk 1 above)
Comment (ivailop7) [reply packages/lexical-playground/src/plugins/ToolbarPlugin/index.tsx:558]: Very good point, will amend!

**Comment by ivailop7** [comment]
@zurfyx are we good with this one?

**Comment by zurfyx** [comment]
> @zurfyx are we good with this one?

Can you check on the test failures please?

**Comment by zurfyx** [comment]
> Ops, my fault. What's the right order of npm commands to repro these tests locally? When I directly run them, all tests fail, while Unit and Integration pass.

You probably want to run `debug-test-e2e-legacy-chromium` and the other similar variants listed in the package.json. The CI variants work with a different port if that's what you're referring to

**Comment by ivailop7** [comment]
@zurfyx All set here.

**Comment by ivailop7** [comment]
@acywatson @zurfyx I think, this one is ready to merge.

**Comment by zurfyx** [comment]
Thank you Ivaylo, sorry for the delay, I completely missed the updated version
