### PR TITLE
[lexical-playground] Bug Fix: Code block formatting in unintended adjacent lines 

### LINKED ISSUE #7691: Bug: Code Block formatting applies to unintended adjacent lines
Lexical version: ^0.32.1, 0.33.1

## Steps To Reproduce

1. In rich-text editor, enter three lines of the text:
aaa
bbb
ccc

2. Select only the middle line (bbb)

3. Apply code block formatting to the selection

4. Observe that the resulting code block unexpectedly includes ccc, instead of just wrapping the selected line

Link to code example: https://playground.lexical.dev/

**Worth noting**: applying a code block to the last line works as expected

https://github.com/user-attachments/assets/94aec4ed-47fd-461e-b8ea-5714382f4b19

### PR DESCRIPTION
**Pull request by achaljhawar**
## Description
Code block formatting was pulling in unselected content after line breaks, this pr fixes this problem by splitting paragraphs at line break boundaries before conversion.

Closes #7691 

### Before

https://github.com/user-attachments/assets/b701e7d8-a936-45cd-b685-a815049f0691

### After

https://github.com/user-attachments/assets/f06fc866-284a-4d07-b532-3a802a76e1aa

### CODE REVIEW

File: packages/lexical-playground/src/plugins/ToolbarPlugin/utils.ts [hunk 1]
```diff
@@ -236,6 +244,64 @@ export const formatQuote = (editor: LexicalEditor, blockType: string) => {
...
+  }
+
+  const newSelection = $createRangeSelection();
+  newSelection.anchor.set(anchorKey, anchorOffset, anchorType);
+  newSelection.focus.set(focusKey, focusOffset, focusType);
+  $setSelection(newSelection);
+}
+
+function $findParagraphParent(
+  node: import('lexical').LexicalNode,
```
Comment (etrepum) [inline packages/lexical-playground/src/plugins/ToolbarPlugin/utils.ts]: This should be a regular type import at the top-level

```suggestion
  node: LexicalNode,
```

**Review by etrepum — APPROVED** [review]
