### PR TITLE
Fix a couple of bugs with Headings creation

### LINKED ISSUE #1170: Heading turns into normal paragraphed text when new line at the front
Similar to #1158 but the other way around is also bugged

In the video:
1. Correct
2. Debatable (Quip works this way but not GDocs, Word nor Pages)
3. Nope, certainly bugged

https://user-images.githubusercontent.com/193447/150975793-ce696608-f3e2-4f58-80b3-48af2b1f5567.mov

### PR DESCRIPTION
**Pull request by thegreatercurve**
On backspace at the start of heading, they shouldn't collapse into a paragraph, and on enter in the middle of a heading, they should stay as a heading.

Closes #1170 #1158

Before 

https://user-images.githubusercontent.com/7748470/204026666-11d75e18-8890-438b-b284-f01853005c62.mov

After

https://user-images.githubusercontent.com/7748470/204026688-55507bcc-3e83-4b5d-91c4-252789c2f894.mov

### CODE REVIEW

File: packages/lexical-rich-text/src/index.ts [hunk 1]
```diff
@@ -297,20 +298,25 @@ export class HeadingNode extends ElementNode {
...
     const direction = this.getDirection();
     newElement.setDirection(direction);
     this.insertAfter(newElement);
     return newElement;
   }
 
-  collapseAtStart(): true {
-    const paragraph = $createParagraphNode();
+  collapseAtStart(selection: RangeSelection): true {
+    const newElement =
```
Comment (trueadm) [inline packages/lexical-rich-text/src/index.ts:313]: Shouldn't this be checking if the prevSibling is an empty element instead of checking the offsets?

File: packages/lexical/flow/Lexical.js.flow [hunk 2]
```diff
@@ -494,7 +494,6 @@ type TextPointType = {
   getNode: () => TextNode,
   set: (key: NodeKey, offset: number, type: 'text' | 'element') => void,
   getCharacterOffset: () => number,
-  isAtNodeEnd: () => boolean,
```
Comment (trueadm) [inline packages/lexical/flow/Lexical.js.flow:497]: Was this never used anywhere? Not even internally?

Comment (thegreatercurve) [reply packages/lexical/flow/Lexical.js.flow:497]: No, it was either never implemented or it has been removed for a while. There's another method called `$isNodeAtEnd` which takes a selection point instead.

File: packages/lexical-rich-text/src/index.ts (hunk 1 above)
Comment (thegreatercurve) [reply packages/lexical-rich-text/src/index.ts]: Yeah, that's probably a better way of doing this one.

**Review by trueadm — APPROVED** [review]
