### PR TITLE
[lexical-code] Bug Fix: Respect RTL when moving to line start/end in code blocks

### LINKED ISSUE #7913: Bug: command+arrow moves to opposite side in RTL in code blocks
Lexical version: v0.37.0+dev.esm

## Steps To Reproduce

1. Write an RTL line, e.g. "איזה כיף" inside a code block
2. Press command+right or command+left

## The current behavior
The caret moves to the opposite end of the paragraph.

## The expected behavior
The caret moves to the correct end of the paragraph.

## Impact of fix
Small impact for RTL users.

### PR DESCRIPTION
**Pull request by ashmod**
## Description

  - Current behavior
      - In code blocks, Command(CTRL)+Left/Right (`MOVE_TO_START`/`END`) on RTL lines moves the caret to the opposite visual end of the line.
  - New behavior
      - Detect the line’s direction and flip `MOVE_TO_START`/`END` semantics for RTL so the caret moves to the correct visual ends.
      - LTR behavior remains unchanged. Non-code content is unaffected.
  - Implementation
      - Add `$getCodeLineDirection`(anchor) in @lexical/code:
          - Scans the code line for the first strong LTR/RTL character across CodeHighlightNode/TabNode segments.
          - Falls back to the parent element’s direction; returns null if indeterminate.
      - Use `$getCodeLineDirection` in both highlighters (Prism, Shiki) to determine whether to invert `MOVE_TO_START/END`

  Closes #7913

  ## Test plan

  ### Before

  - Steps to reproduce
      - Insert a code block; type an RTL string (e.g., "تجربة").
      - Place the caret within the line.
      - Press Command(CTRL)+Left (MOVE_TO_START) or Command(CTRL)+Right (`MOVE_TO_END`).
      - Caret jumps to the opposite visual end of the line.
  - Automated tests
      - No RTL-specific unit coverage in code blocks for `MOVE_TO_START`/`END`.

  ### After

  - Steps to verify
      - Repeat the steps above.
      - `MOVE_TO_START` moves caret to visual left; `MOVE_TO_END` moves caret to visual right on RTL lines.
      - LTR lines behave as before.
  - Automated tests
      - Added RTL test cases to `LexicalCodeNode.test.ts`

### CODE REVIEW

File: packages/lexical-code/src/index.ts [hunk 1]
```diff
@@ -53,3 +55,5 @@ export const getLastCodeNodeOfLine = $getLastCodeNodeOfLine;
 export const getEndOfCodeInLine = $getEndOfCodeInLine;
 /** @deprecated renamed to {@link $getStartOfCodeInLine} by @lexical/eslint-plugin rules-of-lexical */
 export const getStartOfCodeInLine = $getStartOfCodeInLine;
+/** @deprecated renamed to {@link $getCodeLineDirection} by @lexical/eslint-plugin rules-of-lexical */
+export const getCodeLineDirection = $getCodeLineDirection;
```
Comment (etrepum) [inline packages/lexical-code/src/index.ts]:
```suggestion
```

It doesn't really make sense to add deprecated APIs that didn't exist before 😆

File: packages/lexical-code/src/FlatStructureUtils.ts [hunk 2]
```diff
@@ -16,11 +16,39 @@ import type {
...
+    const character = text[i];
+    if (RTL_TEXT_REGEX.test(character)) {
+      return 'rtl';
+    }
+    if (LTR_TEXT_REGEX.test(character)) {
+      return 'ltr';
+    }
+  }
+  return null;
+}
```
Comment (etrepum) [inline packages/lexical-code/src/FlatStructureUtils.ts]: All of this could probably be eliminated by exporting and re-using the currently internal utility function `getTextDirection` from the lexical package

Comment (ashmod) [reply packages/lexical-code/src/FlatStructureUtils.ts]: updated in [12665e9](https://github.com/facebook/lexical/pull/7921/commits/12665e9e008a1d75456b53524670b770378fb5dc)

File: packages/lexical-code/src/FlatStructureUtils.ts [hunk 3]
```diff
@@ -51,6 +57,50 @@ export function $getLastCodeNodeOfLine(
...
+
+  while (node !== null) {
+    if ($isCodeHighlightNode(node)) {
+      const text = node.getTextContent();
+      for (let i = 0; i < text.length; i++) {
+        const direction = getTextDirection(text[i]);
+        if (direction !== null) {
+          return direction;
+        }
+      }
```
Comment (etrepum) [inline packages/lexical-code/src/FlatStructureUtils.ts]: It's very inefficient (and less correct) to do this one code unit at a time

```suggestion
      const direction = getTextDirection(node.getTextContent());
      if (direction !== null) {
        return direction;
      }
```

Comment (ashmod) [reply packages/lexical-code/src/FlatStructureUtils.ts]: Thanks, I've applied this. I initially thought `getTextDirection` would need to be called per unit since it looks up the first RTL character, which I assumed might break cases where a user types in LTR and then switches to RTL. But it seems to be handled correctly.

**Comment by noamzaks** [comment]
This looks pretty good to me, although I don't have the best knowledge in BiDi specifications it looks familiar.

Thank you! :)
